name: 🔄 Daily Dashboard Update

permissions:
  contents: write # needed for committing updated dashboard files
  pages: write # needed for GitHub Pages deployment
  id-token: write # required by actions/configure-pages

on:
  push:
    branches:
      - main

  schedule:
    - cron: "30 3 * * *" # runs at 03:30 UTC → 05:30 CEST (Tirana) each day

  workflow_dispatch: {} # allows manual triggering

jobs:
  update-dashboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install system dependencies & Python libs
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Generate dashboard
        run: python generate_dashboard.py

      - name: Commit updated dashboard & data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: daily dashboard update"
          branch: main
          file_pattern: |
            docs/index.html
            docs/static/graphs/*.png
            historical_indices.csv

  deploy-pages:
    needs: update-dashboard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
