# .github/workflows/build-and-deploy-dashboard.yml

name: 🔄 Build & Deploy Dashboard

# Grant this workflow permission to push content and deploy Pages
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    name: Build Dashboard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate dashboard
        run: python3 generate_dashboard.py

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4 # this is the correct action for uploading build outputs
        with:
          name: docs
          path: docs

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1 # ← revert back to v1
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
