name: "🔄 Daily Dashboard Update"

permissions:
  contents: write # to commit updated data file
  pages: write # to deploy via Pages API
  id-token: write # for configure-pages

on:
  schedule:
    - cron: "30 3 * * *" # every day at 03:30 UTC
  workflow_dispatch: {} # manual trigger

jobs:
  update-dashboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true # we need to push back

      - name: Configure Git for bot commits
        run: |
          git config user.name "dashboard-update-bot"
          git config user.email "dashboard-update-bot@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install system & Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install folium branca

      - name: Scrape data & build dashboard
        run: |
          python scraper.py
          python generate_dashboard.py

      - name: Commit & push historical data only
        run: |
          git add historical_indices.csv
          if ! git diff --cached --quiet; then
            git commit -m "chore: update historical indices"
            git push origin main
          fi

  deploy-pages:
    needs: update-dashboard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (for Pages API)
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
