name: 🔄 Daily Dashboard Update

permissions:
  contents: write # allows committing changes if needed
  pages: write # required by deploy-pages@v4
  id-token: write # required for OIDC with deploy-pages

on:
  schedule:
    - cron: "30 3 * * *" # daily at 03:30 UTC / 05:30 EET
  workflow_dispatch: {} # adds a “Run workflow” button

jobs:
  build_and_deploy:
    name: Build & Deploy Dashboard
    runs-on: ubuntu-latest
    environment:
      name: github-pages # must exist in repo settings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate dashboard
        run: python3 generate_dashboard.py

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
