name: Daily Real-Estate Dashboard

on:
  schedule:
    - cron: '0 1 * * *'   # 01:00 UTC ≈ 03:00 CET

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with: python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scraper
      run: python scraper.py

    - name: Generate Dashboard
      run: python generate_dashboard.py

    - name: Commit & Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'chore(dashboard): daily update'
        file_pattern: |
          docs/dashboard.html
          docs/static/graphs/*.png
          historical_indices.csv
