name: "🔄 Daily Dashboard Update"

permissions:
  contents: write # for the commit step
  pages: write # for the Pages deploy
  id-token: write # required by configure-pages

on:
  schedule:
    - cron: "30 3 * * *" # 03:30 UTC → 05:30 CEST daily
  workflow_dispatch: {} # manual trigger

jobs:
  update-dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install system & Python deps
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install folium branca

      - name: Scrape & build
        run: |
          python scraper.py
          python generate_dashboard.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html docs/heatmap.html docs/static/graphs/*.png historical_indices.csv
          if ! git diff --cached --quiet; then
            git commit -m "chore: daily dashboard update"
            git push origin main
          fi

  deploy-pages:
    needs: update-dashboard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      - uses: actions/deploy-pages@v1
