name: 🔄 Daily Dashboard Update

permissions:
  contents: write

on:
  push:
    branches:
      - main

  schedule:
    - cron: "30 3 * * *" # runs at 03:30 UTC → 05:30 CEST (Tirana) each day

  workflow_dispatch: {}

jobs:
  update-dashboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install system dependencies & Python libs
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Generate dashboard
        run: python generate_dashboard.py

      - name: Commit updated dashboard & data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: daily dashboard update"
          branch: main
          file_pattern: |
            docs/index.html
            docs/static/graphs/*.png
            historical_indices.csv
