name: "🔄 Daily Dashboard Update"

permissions:
  contents: write # needed to commit updated files
  pages: write # needed to deploy to Pages
  id-token: write # needed by configure-pages

on:
  schedule:
    - cron: "30 3 * * *" # every day at 03:30 UTC
  workflow_dispatch: {} # manual trigger

jobs:
  update-dashboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install system & Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install folium branca

      - name: Scrape data & build dashboard
        run: |
          python scraper.py
          python generate_dashboard.py

      - name: Commit & push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html docs/heatmap.html docs/static/graphs/*.png historical_indices.csv
          if ! git diff --cached --quiet; then
            git commit -m "chore: daily dashboard update"
            git push origin main
          fi

  deploy-pages:
    needs: update-dashboard
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
